### PR TITLE
avoid triggering our own deprecation notice

### LINKED ISSUE #363: 3.3.0 throwing strange deprecation notices
Seeing some strange deprecation notices since updating

### Environment

dev (eng)

#### Sonata packages

```bash
 sonata-project/admin-bundle                  3.12.0            
  sonata-project/block-bundle                  3.3.0             
  sonata-project/cache                         1.0.7             
  sonata-project/core-bundle                   3.2.0             
  sonata-project/datagrid-bundle               2.2               
  sonata-project/doctrine-extensions           dev-master fbaff00
  sonata-project/doctrine-orm-admin-bundle     dev-master ab4ba73
  sonata-project/easy-extends-bundle           dev-master 36bac7e
  sonata-project/exporter                      1.7.0         
```

#### Symfony packages

```bash
  symfony/assetic-bundle                       dev-master 0241b13
  symfony/monolog-bundle                       v3.0.3            
  symfony/phpunit-bridge                       v3.2.2            
  symfony/polyfill-intl-icu                    v1.3.0            
  symfony/polyfill-mbstring                    v1.3.0            
  symfony/polyfill-php54                       v1.3.0            
  symfony/polyfill-php56                       v1.3.0            
  symfony/polyfill-php70                       v1.3.0            
  symfony/polyfill-util                        v1.3.0            
  symfony/psr-http-message-bridge              v0.3              
  symfony/security-acl                         v3.0.0            
  symfony/swiftmailer-bundle                   v2.4.2            
```

#### PHP version

```bash
$ php -v
PHP 7.0.15 (cli) (built: Feb  1 2017 01:00:04) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
    with Zend OPcache v7.0.15, Copyright (c) 1999-2017, by Zend Technologies```
```

## Subject
See the deprecation notices I'm seeing.

I'm not using any custom blocks at this point.

## Steps to reproduce
run phpunit on a clean cache

## Expected results
no sonata deprecation notices

## Actual results
```
Using different service id and block id is deprecated since 3.x and will be removed in 4.0: 6x
```

Coming from file: vendor/sonata-project/block-bundle/DependencyInjection/Compiler/TweakCompilerPass.php

```php
            if (strlen($arguments[0]) == 0) {
                $definition->replaceArgument(0, $id);
            } elseif ($id != $arguments[0]) {
                // NEXT_MAJOR: Remove deprecation notice
                @trigger_error(
                    'Using different service id and block id is deprecated since 3.x and will be removed in 4.0.',
                    E_USER_DEPRECATED
                );
            }
```

Potentially useful debugging information

```php
$id = "sonata.block.service.container";
$arguments = 
[ 'sonata.block.container', {Symfony\Component\DependencyInjection\Reference} [ "id" => "templating", "invalidBehavior" => 1 ]];

```

### PR DESCRIPTION
**Pull request by dbu**
I am targetting this branch, because the problem is with this branch.

Closes #363 

## Subject

Do not throw deprecation notices for code that is in this bundle (and will only be fixed for version 4).

## Changelog

```markdown
# Fixed
- Some unwanted deprecation notices about code we can't change until next major version have been removed
```

### CODE REVIEW

**Comment by core23** [comment]
Please add a changelog entry for this

File: DependencyInjection/Compiler/TweakCompilerPass.php [hunk 1]
```diff
@@ -40,7 +40,7 @@ public function process(ContainerBuilder $container)
             // Replace empty block id with service id
             if (strlen($arguments[0]) == 0) {
                 $definition->replaceArgument(0, $id);
-            } elseif ($id != $arguments[0]) {
+            } elseif ($id != $arguments[0] && 0 !== strpos('Sonata\\BlockBundle\\Block\\Service\\', $definition->getClass())) {
```
Comment (dbu) [inline DependencyInjection/Compiler/TweakCompilerPass.php]: using the class rather than the service id. people are good at copy-pasting and might just use sonata.block.service for their own services where we want the deprecation notice

**Comment by dbu** [comment]
> Please add a changelog entry for this

really? i would consider that a pedantic change. there is no behaviour
change at all, only something for continous integration tools.

**Comment by greg0ire** [comment]
If people outside our group get something from it, it's not pedantic and warrants a changelog in this form : 

```
# Fixed
- Some unwanted deprecation notices about <insert whatever is right here> have been removed
```

**Comment by greg0ire** [comment]
@dbu : wrote a changelog for you, I hope you can see some people might read it and think "At last! If I upgrade I'll get rid of this deprecation notices that bug me!"

**Comment by dbu** [comment]
okay, fair enough.

**Comment by greg0ire** [comment]
FYI deprecations is something users are really concerned about : http://stackoverflow.com/questions/40101753/deprecated-warnings-when-using-sonata-admin-bundle

**Comment by dbu** [comment]
and they better be concerned. so we better not teach them that they are
irrelevant :-)

**Comment by greg0ire** [comment]
My thoughts exactly!

**Comment by greg0ire** [comment]
Also, [I wrote a PR to be able to avoid contributions that introduce deprecation without fixing corresponding calls](https://github.com/symfony/symfony/pull/21539), while still being able to ignore deprecations from vendors. Any review / support is very welcome!

**Comment by dbu** [comment]
great one. we have configuration for the deprecation warner with the
number of deprecations triggered by vendors, which is stupid.

**Comment by greg0ire** [comment]
Thanks! Maintaining a number is indeed cumbersome, and if you have several repos like in Sonata, you have to do that for every repo… not a great workflow :P

**Comment by greg0ire** [comment]
Thanks @dbu

**Comment by pkruithof** [comment]
Unfortunately the definition class is `%sonata.block.service.container.class%` rather than a FQCN, so this patch does not work yet :(

**Comment by greg0ire** [comment]
@pkruithof you mean this parameter is not resolved at that time?

**Comment by pkruithof** [comment]
That's what I mean, yes. I upgraded to this version, and the problem remained. Debugging the `$definition->getClass()` call yields this string.

**Comment by greg0ire** [comment]
IIRC there is a resolve or similar method that could be used there… can you check?

**Comment by pkruithof** [comment]
Yes, you can use this:

```php
$class = $container->getParameterBag()->resolveValue($definition->getClass());
if ($id != $arguments[0] && 0 !== strpos('Sonata\\BlockBundle\\Block\\Service\\', $class)) {
```

**Comment by greg0ire** [comment]
Can you make a PR to contribute this?

**Comment by greg0ire** [comment]
Not sure why it worked for @dbu though… unless this parameter was introduced recently? Can you check again @pkruithof ?

**Comment by pkruithof** [comment]
As far as I can see there is no test for this class, so my guess would be that this change was not tested.

**Comment by dbu** [comment]
yep, i don't think i really tested it.

**Comment by pkruithof** [comment]
PR => https://github.com/sonata-project/SonataBlockBundle/pull/369

**Comment by greg0ire** [comment]
> yep, i don't think i really tested it.

Won't blame you , I do that way too often :P

**Comment by dbu** [comment]
thanks for fixing it and sorry again.
