### PR TITLE
Override and use Extension::getConfiguration method

### LINKED ISSUE #303: Console config:dump error
| Question       | Answer
|----------------|-------------------------------
| BundleVersion | dev-master dbc70ca
| SymfonyVersion | v2.8.2
| PhpVersion | PHP 5.6.10

# Error message

[LogicException]                                                                           
The extension with alias "sonata_block" does not have its getConfiguration() method setup

# Steps to reproduce
config:dump SonataBlockBundle

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #303 

### Changelog

```markdown
### Fixed
- Error with the default extension configuration for `config:dump-reference` command
```

### Subject

The `Configuration` class constructor needs `$defaultContainerTemplates` argument.

This is not provided on the default `Extension::getConfiguration` method.

The bundle is working, but some functionalities like `app/console config:dump-reference sonata_block` might fail.

@stphnpt can you please confirm this fix your issue?

### CODE REVIEW

File: DependencyInjection/SonataBlockExtension.php [hunk 1]
```diff
@@ -30,7 +30,7 @@ class SonataBlockExtension extends Extension
     /**
```
Comment (stphnpt) [inline DependencyInjection/SonataBlockExtension.php]: Comment says "PageExtension" shall be "BlockExtension"

**Comment by Soullivaneuh** [comment]
> Comment line 23 says "PageExtension" shall be "BlockExtension"

Please don't add a comment on irrelevant line.

This is not related to the PR but I could add an extra commit.

Can you confirm this solve your issue?

**Comment by stphnpt** [comment]
> Can you confirm this solve your issue?

Yes ! Thank you very much.

**Comment by OskarStark** [comment]
Can i merge @Soullivaneuh ?

**Comment by Soullivaneuh** [comment]
@OskarStark merge what? :trollface:

**Comment by OskarStark** [comment]
> @OskarStark merge what? :trollface:

😄  good job 👍

**Comment by Soullivaneuh** [comment]
https://github.com/sonata-project/SonataBlockBundle/releases/tag/3.0.1
